package ru.voodoo420.client;

public enum State {
    WAITING,
    RECEIVING_FILE_NAME_LENGTH,
    RECEIVING_FILE_NAME,
    RECEIVING_FILE_LENGTH,
    RECEIVING_FILE,
    RECEIVING_MESSAGE
//    RECEIVING_FILE_TO_DELETE_NAME_LENGTH,
//    RECEIVING_FILE_TO_DELETE_NAME;
}
