package ru.voodoo420.server;

public enum State {
    WAITING,
    RECEIVING_FILE_TO_RECEIVE_NAME_LENGTH,
    RECEIVING_FILE_TO_SEND_NAME_LENGTH,
    RECEIVING_FILE_TO_DELETE_NAME_LENGTH,
    RECEIVING_FILE_NAME,
    RECEIVING_FILE_LENGTH,
    RECEIVING_FILE,
    DELETING_FILE,
    SENDING_FILE,
    SENDING_FILES_LIST
}
