package ru.voodoo420.server;

public enum State {
    //todo переобозвать
    WAITING,
    RECEIVING_FILE_TO_RECEIVE_NAME_LENGTH,
    RECEIVING_FILE_TO_RECEIVE_NAME,
    RECEIVING_FILE_TO_RECEIVE_LENGTH,
    RECEIVING_FILE,
    RECEIVING_FILE_TO_DELETE_NAME_LENGTH,
    RECEIVING_FILE_TO_DELETE_NAME,
    RECEIVING_FILE_TO_SEND_NAME_LENGTH,
    RECEIVING_FILE_TO_SEND_NAME
}
